import { MarketIndex } from "../types/stock";

// NGX-specific indices
export const NGX_INDICES: MarketIndex[] = [
  {
    id: "ngx-asi",
    name: "NGX All Share Index",
    value: 65432.18,
    change: 234.56,
    percentChange: 0.36,
    market: "NGX",
  },
  {
    id: "ngx-banking",
    name: "NGX Banking Index",
    value: 543.21,
    change: 12.34,
    percentChange: 2.32,
    market: "NGX",
  },
  {
    id: "ngx-30",
    name: "NGX 30 Index",
    value: 2345.67,
    change: -15.43,
    percentChange: -0.65,
    market: "NGX",
  },
  {
    id: "ngx-industrial",
    name: "NGX Industrial Goods Index",
    value: 3456.78,
    change: 45.67,
    percentChange: 1.34,
    market: "NGX",
  },
  {
    id: "ngx-oil-gas",
    name: "NGX Oil & Gas Index",
    value: 876.54,
    change: -5.43,
    percentChange: -0.62,
    market: "NGX",
  },
  {
    id: "ngx-consumer",
    name: "NGX Consumer Goods Index",
    value: 1234.56,
    change: 7.89,
    percentChange: 0.64,
    market: "NGX",
  },
];

// Mock data for NGX stocks to be used in the bubble chart
export const NGX_STOCKS = [
  {
    id: "ngx-dangcem",
    name: "Dangote Cement",
    symbol: "DANGCEM",
    price: 280.50,
    change: 12.50,
    percentChange: 4.66,
    volume: 1234567,
    value: 346345743.5,
    trades: 234,
    sector: "Industrial",
    market: "NGX",
    logo: "/logos/dangcem.png"
  },
  {
    id: "ngx-mtnn",
    name: "MTN Nigeria",
    symbol: "MTNN",
    price: 178.20,
    change: 5.30,
    percentChange: 3.06,
    volume: 987654,
    value: 175999826.8,
    trades: 312,
    sector: "Telecommunications",
    market: "NGX",
    logo: "/logos/mtnn.png"
  },
  {
    id: "ngx-zenithbank",
    name: "Zenith Bank",
    symbol: "ZENITHBANK",
    price: 24.85,
    change: 0.85,
    percentChange: 3.54,
    volume: 2345678,
    value: 58290099.3,
    trades: 456,
    sector: "Financial Services",
    market: "NGX",
    logo: "/logos/zenithbank.png"
  },
  {
    id: "ngx-nestle",
    name: "Nestle Nigeria",
    symbol: "NESTLE",
    price: 1050.00,
    change: -25.50,
    percentChange: -2.37,
    volume: 123456,
    value: 129628800,
    trades: 178,
    sector: "Consumer Goods",
    market: "NGX",
    logo: "/logos/nestle.png"
  },
  {
    id: "ngx-gtco",
    name: "Guaranty Trust Holding",
    symbol: "GTCO",
    price: 32.45,
    change: 1.20,
    percentChange: 3.84,
    volume: 1876543,
    value: 60894320.35,
    trades: 387,
    sector: "Financial Services",
    market: "NGX",
    logo: "/logos/gtco.png"
  },
  {
    id: "ngx-airtel",
    name: "Airtel Africa",
    symbol: "AIRTELAFRI",
    price: 1642.80,
    change: -32.60,
    percentChange: -1.95,
    volume: 98765,
    value: 162246162,
    trades: 145,
    sector: "Telecommunications",
    market: "NGX",
    logo: "/logos/airtel.png"
  },
  {
    id: "ngx-buacement",
    name: "BUA Cement",
    symbol: "BUACEMENT",
    price: 95.75,
    change: 2.25,
    percentChange: 2.41,
    volume: 543210,
    value: 52012357.5,
    trades: 231,
    sector: "Industrial",
    market: "NGX",
    logo: "/logos/buacement.png"
  },
  {
    id: "ngx-fbnh",
    name: "FBN Holdings",
    symbol: "FBNH",
    price: 16.80,
    change: -0.45,
    percentChange: -2.61,
    volume: 3456789,
    value: 58074055.2,
    trades: 423,
    sector: "Financial Services",
    market: "NGX",
    logo: "/logos/fbnh.png"
  },
  {
    id: "ngx-uacn",
    name: "UAC of Nigeria",
    symbol: "UACN",
    price: 12.35,
    change: 0.15,
    percentChange: 1.23,
    volume: 765432,
    value: 9453085.2,
    trades: 198,
    sector: "Conglomerate",
    market: "NGX",
    logo: "/logos/uacn.png"
  },
  {
    id: "ngx-oando",
    name: "Oando",
    symbol: "OANDO",
    price: 8.90,
    change: 0.40,
    percentChange: 4.71,
    volume: 1234567,
    value: 10987646.3,
    trades: 267,
    sector: "Oil & Gas",
    market: "NGX",
    logo: "/logos/oando.png"
  },
];