name: NGX Daily Data Seed

on:
  # Manual trigger
  workflow_dispatch:
  
  # Scheduled trigger - 5 PM WAT (West Africa Time, UTC+1) Monday-Friday
  schedule:
    - cron: '0 16 * * 1-5'  # 16:00 UTC = 17:00 WAT

jobs:
  seed-ngx-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma client
        run: npx prisma generate
        
      - name: Seed NGX daily data
        run: |
          curl -X POST ${{ secrets.API_URL }}/api/seed/ngx-daily \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            --fail
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}